export const HEARTBEAT = 'VIDEOWIKI_HEARTBEAT';
export const HUMANVOICE_AUDIO_PROCESSING = 'HUMANVOICE_AUDIO_PROCESSING';
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';
export const RECORDED_AUDIO_PROCESSED = 'RECORDED_AUDIO_PROCESSED';
