export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS';
export const INVITE_USER_ERROR = 'INVITE_USER_ERROR';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const CHANGE_PERMISSION_SUCCESS = 'CHANGE_PERMISSION_SUCCESS';