export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS';
export const INVITE_USER_ERROR = 'INVITE_USER_ERROR';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const CHANGE_PERMISSION_SUCCESS = 'CHANGE_PERMISSION_SUCCESS';

export const SET_ORGANIZATION = 'SET_ORGANIZATION';

export const SET_NEW_ORGANIZATION_NAME = 'SET_NEW_ORGANIZATION_NAME';
export const SET_NEW_ORGANIZATION_LOGO = 'SET_NEW_ORGANIZATION_LOGO';
export const SET_CREATE_ORGANIZATION_LOADING = 'SET_CREATE_ORGANIZATION_LOADING';
export const SET_UPLOAD_LOGO_LOADING = 'SET_UPLOAD_LOGO_LOADING';
