export const FETCH_ARTICLE_LOADING = 'FETCH_ARTICLE_LOADING';
export const FETCH_ARTICLE_FAILED = 'FETCH_ARTICLE_FAILED';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';

export const UPDATE_SUBSLIDE_LOADING = 'UPDATE_SUBSLIDE_LOADING';
export const UPDATE_SUBSLIDE_FAILED = 'UPDATE_SUBSLIDE_FAILED';
export const UPDATE_SUBSLIDE_SUCCESS = 'UPDATE_SUBSLIDE_SUCCESS';

export const SET_SUBTITLES = 'SET_SUBTITLES';
export const SET_ARTICLE = 'SET_ARTCILE';
export const SET_SELECTED_SUBTITLE = 'SET_SELECTED_SUBTITLE';

export const SET_TO_ENGLISH = 'SET_TO_ENGLISH';