const MODULE_PREFIX = 'ORGANIZATION/VIDEOS';

export const SET_ACTIVE_TAB_INDEX = `${MODULE_PREFIX}/SET_ACTIVE_TAB_INDEX`

export const SET_VIDEO_LOADING = `${MODULE_PREFIX}/SET_VIDEO_LOADING`;
export const SET_VIDEOS = `${MODULE_PREFIX}/SET_VIDEOS`;

export const SET_LANGUAGE_FILTER = `${MODULE_PREFIX}/SET_LANGUAGE_FILTER`
export const SET_SELECTED_VIDEO = `${MODULE_PREFIX}/SET_SELECTED_VIDEO`;
export const SET_ADD_HUMAN_VOICE_MODAL_VISIBLE = `${MODULE_PREFIX}/SET_ADD_HUMAN_VOICE_MODAL_VISIBLE`;

export const SET_TRANSLATED_ARTICLES = `${MODULE_PREFIX}/SET_TRANSLATED_ARTICLES`;