const MODULE_PREFIX = `INVITATIONS`;

export const SET_LOADING = `${MODULE_PREFIX}/SET_LOADING`;
export const SET_SHOW_PASSWORD_FORM = `${MODULE_PREFIX}/SET_SHOW_PASSWORD_FORM`;
export const SET_PASSWORD = `${MODULE_PREFIX}/SET_PASSWORD`;
export const SET_PASSWORD_CONFIRM = `${MODULE_PREFIX}/SET_PASSWORD_CONFIRM`;
export const SET_OLD_PASSWORD = `${MODULE_PREFIX}/SET_OLD_PASSWORD`;

export const SET_PASSWORD_LOADING = `${MODULE_PREFIX}/SET_PASSWORD_LOADING`;
export const SET_USER = `${MODULE_PREFIX}/SET_USER`;
