export const UPLOAD_VIDEO_LOADING = 'UPLOAD_VIDEO_LOADING';
export const UPLOAD_VIDEO_FAILED = 'UPLOAD_VIDEO_FAILED';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_PROGRESS = 'UPLOAD_VIDEO_PROGRESS';