const MODULE_PREFIX = `VIDEO`

export const UPLOAD_VIDEO_LOADING = `${MODULE_PREFIX}/UPLOAD_VIDEO_LOADING`;
export const UPLOAD_VIDEO_FAILED = `${MODULE_PREFIX}/UPLOAD_VIDEO_FAILED`;
export const UPLOAD_VIDEO_SUCCESS = `${MODULE_PREFIX}/UPLOAD_VIDEO_SUCCESS`;
export const UPLOAD_VIDEO_PROGRESS = `${MODULE_PREFIX}/UPLOAD_VIDEO_PROGRESS`;
export const FETCH_VIDEO_LOADING = `${MODULE_PREFIX}/FETCH_VIDEO_LOADING`;
export const FETCH_VIDEO_FAILED = `${MODULE_PREFIX}/FETCH_VIDEO_FAILED`;
export const FETCH_VIDEO_SUCCESS = `${MODULE_PREFIX}/FETCH_VIDEO_SUCCESS`;

export const SET_STAGES = `${MODULE_PREFIX}/SET_STAGES`;

export const FETCH_ORGANIZATION_VIDEOS_LOADING = `${MODULE_PREFIX}/FETCH_ORGANIZATION_VIDEOS_LOADING`;
export const FETCH_ORGANIZATION_VIDEOS_SUCCESS = `${MODULE_PREFIX}/FETCH_ORGANIZATION_VIDEOS_SUCCESS`;
export const FETCH_ORGANIZATION_VIDEOS_FAILED = `${MODULE_PREFIX}/FETCH_ORGANIZATION_VIDEOS_FAILED`;

export const SET_ORGANIZATION_VIDEOS_ACTIVE_TAB_INDEX = `${MODULE_PREFIX}/SET_ORGANIZATION_VIDEOS_ACTIVE_TAB_INDEX`;
export const SET_ORGANIZATION_VIDEOS_TABS = `${MODULE_PREFIX}/SET_ORGANIZATION_VIDEOS_TABS`;

export const RESET = `${MODULE_PREFIX}/RESET`;
export const RESET_UPLOAD_VIDEO_FORM = `${MODULE_PREFIX}/RESET_UPLOAD_VIDEO_FORM`;

export const SET_UPLOAD_VIDEO_FORM = `${MODULE_PREFIX}/SET_UPLOAD_VIDEO_FORM`;