export const UPLOAD_VIDEO_LOADING = 'UPLOAD_VIDEO_LOADING';
export const UPLOAD_VIDEO_FAILED = 'UPLOAD_VIDEO_FAILED';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_PROGRESS = 'UPLOAD_VIDEO_PROGRESS';
export const FETCH_VIDEO_LOADING = 'FETCH_VIDEO_LOADING';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';

export const SET_STAGES = 'SET_STAGES';

export const FETCH_ORGANIZATION_VIDEOS_LOADING = 'FETCH_ORGANIZATION_VIDEOS_LOADING';
export const FETCH_ORGANIZATION_VIDEOS_SUCCESS = 'FETCH_ORGANIZATION_VIDEOS_SUCCESS';
export const FETCH_ORGANIZATION_VIDEOS_FAILED = 'FETCH_ORGANIZATION_VIDEOS_FAILED';

export const SET_ORGANIZATION_VIDEOS_ACTIVE_TAB_INDEX = 'SET_ORGANIZATION_VIDEOS_ACTIVE_TAB_INDEX';

export const RESET = 'VIDEO/RESET';